<?php require('template/header.phtml') ?>

<h3>Welcome to the Map Page</h3>
<p>
    This map allows you to track the location of mutually accepted friends in real time.
</p>

<p id="output"></p>

<div id="Map" style="width:800px;height:600px"></div>
<script src="/OpenLayers-2.13.1/OpenLayers.js"></script>
<script>
    var locations = [
      ['Manly Beach', -33.800101, 151.28747820],['Bondi Beach', -33.890542, 151.157507]
    ];

    map = new OpenLayers.Map("Map");
    map.addLayer(new OpenLayers.Layer.OSM());

    var lonLat = new OpenLayers.LonLat( 151.274856,-33.89).transform(new OpenLayers.Projection("EPSG:4326"), map.getProjectionObject());

    var zoom=10;

    var markers = new OpenLayers.Layer.Markers( "Markers" );
    map.addLayer(markers);

    function createMarker(item)
    {
        //Test
        console.log[item[0], item[1], item[2]];
        //Creating Marker
        let mposition = new OpenLayers.LonLat( item[2] ,item[1] ).transform(new OpenLayers.Projection("EPSG:4326"), map.getProjectionObject());
        markers.addMarker(new OpenLayers.Marker(mposition));
    }

    locations.forEach(createMarker);

    map.setCenter (lonLat, zoom);
</script>

<script>
    function success() {
        console.log("Success");
    }

    function error() {
        console.log("Failure");
    }

    function giveCoordinates(lat,long)
    {
        var out = document.getElementById("output");
        out.innerHTML = "Your Latitude is " + lat + " and your Longitude is " + long;

        document.cookie = 'latitude = ' + lat;
        document.cookie = 'longitude = ' + long;
    }

    navigator.geolocation.getCurrentPosition(function (position)
    {
        giveCoordinates(position.coords.latitude,position.coords.longitude);
    });
</script>

</div>
<?php require('template/footer.phtml') ?>
