<?php require('template/header.phtml') ?>

<h3>Welcome to the Map Page</h3>
<p>
    <?php
    if (isset($_SESSION['loggedIn'])) {
        echo 'This map allows you to track the location of mutually accepted friends in real time. The blue marker is you and the red markers are your 
        friends. Click the markers to obtain the friend\'s information.';
    } else {
        echo 'You need to be logged in to use the map.';
    }
     ?>
</p>
<div id="Map" onmouseenter="loadFriends()" 	class=".col-lg-10"<?php if(!isset($_SESSION['loggedIn'])) {echo 'hidden';}?>></div>
<script src="/OpenLayers-2.13.1/OpenLayers.js"></script>
<script>
    var friends = [];
    function loadFriends(){
        var xmlhttp = new XMLHttpRequest();

        xmlhttp.onreadystatechange = function () {
            if(this.readyState == 4 && this.status == 200) {
                if(this.response.length !== 0)
                {
                    //console.log(this.response);
                    friends = JSON.parse(this.responseText);
                    //console.log(friends);
                    vectorLayer.destroyFeatures();
                    createUserFeature();
                    friends.forEach(createFriendFeatures);
                    map.addLayer(vectorLayer);
                }
            }
        }
        xmlhttp.open("GET", "friendsajax.php?check=friend", false);
        xmlhttp.send();
    }

    map = new OpenLayers.Map("Map");
    mapnik = new OpenLayers.Layer.OSM();
    map.addLayer(mapnik);

    epsg4326 =  new OpenLayers.Projection("EPSG:4326"); //WGS 1984 projection
    projectTo = map.getProjectionObject(); //The map projection (Spherical Mercator)

    var lonLat = new OpenLayers.LonLat( <?php echo $_SESSION['user'][7]?>, <?php echo $_SESSION['user'][6]?>).transform(epsg4326, projectTo);

    var zoom=12;
    //Code to set the map
    map.setCenter (lonLat, zoom);

    var vectorLayer = new OpenLayers.Layer.Vector("Overlay");

    //Define markers as "features" of the vector layer
    function createUserFeature()
    {
        var userFeature = new OpenLayers.Feature.Vector(
            new OpenLayers.Geometry.Point( <?php echo $_SESSION['user'][7]?>, <?php echo $_SESSION['user'][6]?>).transform(epsg4326, projectTo),
            {description:'This is you.'} ,
            {externalGraphic: '../images/user.png', graphicHeight: 25, graphicWidth: 21, graphicXOffset:-12, graphicYOffset:-25  }
        );
        vectorLayer.addFeatures(userFeature);
    }

    function createFriendFeatures(friend)
    {
        //Test
        console.log(friend.username);
        //Creating Marker
        var friendFeature = new OpenLayers.Feature.Vector(
            new OpenLayers.Geometry.Point( friend.longitude, friend.latitude ).transform(epsg4326, projectTo),
            {description:'<img style="max-width: 50px; align-items: center" src="' + friend.profilePicture +'">' + ' <p> Username: ' + friend.username + '</p>' + ' <p> Name: ' + friend.name + '</p>' + ' <p> Latitude: ' + friend.latitude + '</p>' + ' <p> Longitude: ' + friend.longitude + '</p>'} ,
            {externalGraphic: '../images/marker.png', graphicHeight: 25, graphicWidth: 21, graphicXOffset:-12, graphicYOffset:-25  }
        );
        vectorLayer.addFeatures(friendFeature);
    }

    map.addLayer(vectorLayer);

    //Add a selector control to the vectorLayer with popup functions
    var controls = {
        selector: new OpenLayers.Control.SelectFeature(vectorLayer, { onSelect: createPopup, onUnselect: destroyPopup })
    };

    function createPopup(feature) {
        feature.popup = new OpenLayers.Popup.FramedCloud("pop",
            feature.geometry.getBounds().getCenterLonLat(),
            null,
            '<div class="markerContent">'+feature.attributes.description+'</div>',
            null,
            true,
            function() { controls['selector'].unselectAll(); }
        );
        //feature.popup.closeOnMove = true;
        map.addPopup(feature.popup);
    }

    function destroyPopup(feature) {
        feature.popup.destroy();
        feature.popup = null;
    }

    map.addControl(controls['selector']);
    controls['selector'].activate();

    loadFriends();
</script>

</div>
<?php require('template/footer.phtml') ?>
