<?php require('template/header.phtml') ?>
    <h3>Search</h3>
    <p>
        <?php echo $resultsMessage //global variable that is set by the controller?>
    </p>
    <hr>
    <h3>List of users!</h3>
    <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post" id="table">
        <div class="col-auto">
            <table class="table table-bordered table-responsive">
                <thead>
                <?php
                if (isset($_SESSION['loggedIn'])) {
                    echo '
                          <tr>
                            <th>Profile Picture</th>
                            <th>Username</th>
                            <th>Name</th>
                            <th>Email-Address</th>
                            <th>Activity-Time</th>
                            <th>Latitude</th>
                            <th>Longitude</th>
                            <th></th>
                          </tr>
                </thead>
                <tbody>';
                    function hidden($username, $comparison) //function echo hidden if the user's username and the data's username is the same
                    {
                        $hidden = "";
                        if($username === $comparison)
                            $hidden = "hidden";
                        return $hidden;
                    }
                    if ($_SESSION['loggedIn']) {
                        foreach ($view->usersDataSet as $userData) { //displays all user data if the user is logged in
                            $username = $_SESSION['user'][0];
                            $comparison = $userData->getUsername();
                            echo '<form action="search.php" method="post">' .
                                '<tr><td><img src="' . $userData->getProfilePicture() . '"</td>' .
                                '<td><input type="hidden" name="friend" value="' . $userData->getUsername() .'">' . $userData->getUsername() . '</td>' .
                                '<td>' . $userData->getName() . '</td>' .
                                '<td>' . $userData->getEmailAddress() . '</td>' .
                                '<td>' . $userData->getActivityTime() . '</td>' .
                                '<td>' . $userData->getLatitude() . '</td>' .
                                '<td>' . $userData->getLongitude() . '</td>' .
                                '<td ' .  hidden($username,$comparison) . '><button name="addButton" type="submit">Add</button></td>' .
                                '</tr></form>';
                        }
                    }
                }
                else{
                    echo '
                <tr>
                    <th>Profile Picture</th>
                    <th>Username</th>
                </tr>
                </thead>
                <tbody>';
                        foreach ($view->usersDataSet as $userData) { //this table only displays two sections of user information, if the user is not logged in
                            echo '<tr><td><img src="' . $userData->getProfilePicture() . '"</td>' .
                                '<td>' . $userData->getUsername() . '</td>' .
                                '</tr>';
                        }
                }?>
                </tbody>
            </table>
            <?php
            for($page=1; $page<=$view->numberOfPages;$page++) //creates a page for each number of pages there has been set in the controller
            {
                echo '<a id="paginationNum" href="search.php?page=' . $page . '">' . $page . '</a> ';
            }
            ?>
        </div>
    </form>
    </div>
<?php require('template/footer.phtml') ?>