</div>
    <div class="row">
        <div id="footer" class="col-xs-12">
            <p>
                &#169 Best Teas 2022. Website by Christopher Kearsley-Brown
            </p>
            <!--Copyright protection-->
            <p>The logo is made by iconixar from <a href="https://www.flaticon.com/">flaticon.com</a></p>
            <p>The default user image is made by Freepix from <a href="https://www.flaticon.com/">flaticon.com</a></p>
        </div>
    </div>

</div>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
</body>
</html>